# Generated by Django 4.1.5 on 2023-01-24 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionCorrect', models.CharField(max_length=1000)),
                ('option2', models.CharField(max_length=1000)),
                ('option3', models.CharField(max_length=1000)),
                ('option4', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserTileScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaicaapi.tile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaicaapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=1000)),
                ('spanish', models.CharField(max_length=1000)),
                ('aspect1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspect1', to='mosaicaapi.responseset')),
                ('aspect2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspect2', to='mosaicaapi.responseset')),
                ('aspect3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspect3', to='mosaicaapi.responseset')),
                ('aspect4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspect4', to='mosaicaapi.responseset')),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaicaapi.tile')),
            ],
        ),
        migrations.CreateModel(
            name='BadQuestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDescription', models.CharField(max_length=1000)),
                ('problemCategory', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaicaapi.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaicaapi.user')),
            ],
        ),
    ]
