# Generated by Django 4.1.5 on 2023-01-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaicaapi', '0002_alter_question_aspect1_alter_question_aspect2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertilescore',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
