# Generated by Django 4.1.5 on 2023-01-24 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaicaapi', '0004_alter_usertilescore_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertilescore',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 1, 24, 18, 37, 43, 318404, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
