# Generated by Django 4.1.5 on 2023-01-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaicaapi', '0008_alter_usertilescore_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertilescore',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
